import { SalesDataProps } from "@/types/typesProject";

export const arrSalesCalvin: SalesDataProps[] = [
    {
        id: 1,
        year: 2022,
        quarter: 1,
        revenue: 6.8,
        growth: 5.8,
    },
    {
        id: 2,
        year: 2022,
        quarter: 2,
        revenue: 7.1,
        growth: 6.0,
    },
    {
        id: 3,
        year: 2022,
        quarter: 3,
        revenue: 7.3,
        growth: 6.2,
    },
    {
        id: 4,
        year: 2022,
        quarter: 4,
        revenue: 7.5,
        growth: 7.4,
    },
    {
        id: 5,
        year: 2023,
        quarter: 1,
        revenue: 7.7,
        growth: 8.6,
    },
    {
        id: 6,
        year: 2023,
        quarter: 2,
        revenue: 7.9,
        growth: 8.9,
    },
    {
        id: 7,
        year: 2023,
        quarter: 3,
        revenue: 8.2,
        growth: 10.2,
    },
    {
        id: 8,
        year: 2023,
        quarter: 4,
        revenue: 8.2,
        growth: 12.1,
    },
    {
        id: 9,
        year: 2024,
        quarter: 1,
        revenue: 8.4,
        growth: 16.5,
    },
    {
        id: 10,
        year: 2024,
        quarter: 2,
        revenue: 8.6,
        growth: 16.9,
    },
    {
        id: 11,
        year: 2024,
        quarter: 3,
        revenue: 8.7,
        growth: 17.8,
    },
    {
        id: 12,
        year: 2024,
        quarter: 4,
        revenue: 8.8,
        growth: 4.8,
    },
    {
        id: 13,
        year: 2025,
        quarter: 1,
        revenue: 8.9,
        growth: 4.7,
    },
    {
        id: 14,
        year: 2025,
        quarter: 2,
        revenue: 9.0,
        growth: 3.6,
    },
];