import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Mono } from "next/font/google";

export const roboto_mono = Roboto_Mono({
    subsets: ["latin"],
    style: ["normal"],
    weight: ["400", "700"],
    display: "swap",
});

export const metadata: Metadata = {
    title: "E-commerce / Shop",
    description: "Generated by create next app for shop",
    icons: {
        icon: "/favicon.ico",
        shortcut: "/favicon.ico",
    },
};

export default function BrandsLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html>
    +      <body className={`${roboto_mono.className} bg-white m-0`}>
    +        {children}
    +      </body>
    +    </html>
    );
}