import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Mono } from "next/font/google";
import { CartProvider } from "@/components/cart/cartProvider";

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "E-commerce / Shop",
  description: "Generated by create next app for shop",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto_mono.className} bg-white m-0`}>
        <a href="#main-content" className="skip-link">Skip to main content</a>
        <div id="main-content" tabIndex={-1}>
          <CartProvider>{children}</CartProvider>
        </div>
      </body>
    </html>
  );
}