import { SalesDataProps } from "@/types/typesProject";


export const arrSalesZara: SalesDataProps[] = [
    {
        id: 1,
        year: 2022,
        quarter: 1,
        revenue: 7.8,
        growth: 6.6,
    },
    {
        id: 2,
        year: 2022,
        quarter: 2,
        revenue: 8.1,
        growth: 6.7,
    },
    {
        id: 3,
        year: 2022,
        quarter: 3,
        revenue: 8.3,
        growth: 6.9,
    },
    {
        id: 4,
        year: 2022,
        quarter: 4,
        revenue: 8.4,
        growth: 8.3,
    },
    {
        id: 5,
        year: 2023,
        quarter: 1,
        revenue: 8.7,
        growth: 9.6,
    },
    {
        id: 6,
        year: 2023,
        quarter: 2,
        revenue: 8.9,
        growth: 9.9,
    },
    {
        id: 7,
        year: 2023,
        quarter: 3,
        revenue: 9.1,
        growth: 11.5,
    },
    {
        id: 8,
        year: 2023,
        quarter: 4,
        revenue: 9.1,
        growth: 13.5,
    },
    {
        id: 9,
        year: 2024,
        quarter: 1,
        revenue: 9.3,
        growth: 18.6,
    },
    {
        id: 10,
        year: 2024,
        quarter: 2,
        revenue: 9.5,
        growth: 19.1,
    },
    {
        id: 11,
        year: 2024,
        quarter: 3,
        revenue: 9.6,
        growth: 20.0,
    },
    {
        id: 12,
        year: 2024,
        quarter: 4,
        revenue: 9.7,
        growth: 5.5,
    },
    {
        id: 13,
        year: 2025,
        quarter: 1,
        revenue: 9.8,
        growth: 5.4,
    },
    {
        id: 14,
        year: 2025,
        quarter: 2,
        revenue: 9.9,
        growth: 4.2,
    },
]