//TODO: to debug
//TODO: fix component to check of correct working
//TODO: to check all component ui
//TODO: Fix the brand data fetching logic in case of brand not found issue.
//TODO: Ensure proper capitalization and spacing when deriving brand name from URL slug.
//TODO: Add error handling for invalid brand slugs in the URL.
//TODO: Consider adding a loading spinner or placeholder while brand data is being fetched.
//TODO: fix component to check of correct working

import type { Metadata } from "next";
import "./globals.css";
import {Roboto_Mono} from 'next/font/google';
import NavBar from "@/components/mainPage/navbar";
import Footer from "@/components/mainPage/footer";

export const roboto_mono = Roboto_Mono({
    subsets:['latin'],
    style:['normal'],
    weight: ['400', '700'],
    display: 'swap'
});

export const metadata: Metadata = {
    title: "Shop / Activewear",
    description: "Generated by create next app for shop",
    icons: {
        icon: "/favicon.ico",
        shortcut: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={roboto_mono.className} style={{
                backgroundColor: "white"
            }}>
                <NavBar />
                {children}
            </body>
        </html>
    );
}