import type { Metadata } from "next";
import "../globals.css";
import { Roboto_Mono } from "next/font/google";
import NavBar from "@/components/mainPage/navbar";

const roboto_mono = Roboto_Mono({
    subsets:['latin'],
    style:['normal'],
    weight: ['400', '700'],
    display: 'swap'
});

export const metadata: Metadata = {
    title: "Shop / Activewear",
    description: "Generated by create next app for shop",
    icons: {
        icon: "/favicon.ico",
        shortcut: "/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${roboto_mono.className} bg-white`}>
                <NavBar />
                {children}
        </div>
    );
}